/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyLabel {
        /**
          * The type of the label, can be primary, success, error, warning
         */
        "type": string;
        /**
          * The value of the label
         */
        "value": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyLabelElement extends Components.MyLabel, HTMLStencilElement {
    }
    var HTMLMyLabelElement: {
        prototype: HTMLMyLabelElement;
        new (): HTMLMyLabelElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-label": HTMLMyLabelElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyLabel {
        /**
          * The type of the label, can be primary, success, error, warning
         */
        "type"?: string;
        /**
          * The value of the label
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-label": MyLabel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-label": LocalJSX.MyLabel & JSXBase.HTMLAttributes<HTMLMyLabelElement>;
        }
    }
}
